services:
  apache:
    container_name: "salestio-apache"
    restart: always
    build:
      context: docker-files/apache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/apache2/ssl
      - ./www:/var/www
      - ./logs/apache2:/var/log/apache2:delegated
    depends_on:
      - php8.4
    develop:
      watch:
        - action: rebuild
          path: docker-files/apache/config/panel.conf
        - action: rebuild
          path: docker-files/apache/config/panel-ssl.conf

        - action: rebuild
          path: docker-files/apache/Dockerfile
  db:
    image: mariadb:12.1.2
    container_name: "salestio-db"
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: salestio
    ports:
      - "3306:3306"
    volumes:
      - "./data/mysql:/var/lib/mysql"
  php8.4:
    container_name: "salestio-php"
    restart: always
    build:
      context: docker-files/php8.4
    volumes:
      - "./logs/supervisor/:/var/log/supervisor/:delegated"
      - "./www:/var/www"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    develop:
      watch:
        - action: rebuild
          path: docker-files/php8.4/config/supervisord.conf
        - action: rebuild
          path: docker-files/php8.4/config/fpm-pool.conf
        - action: rebuild
          path: docker-files/php8.4/config/fpm.conf

        - action: rebuild
          path: docker-files/php8.4/Dockerfile
    depends_on:
      - db
    environment:
      APP_KEY: "base64:hGHIdRQ8R0pQjq1QuBDU20JpCF/btcfXr+e1Z7NLgL4="
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: salestio
      DB_USERNAME: root
      DB_PASSWORD: password
  swagger:
    container_name: "salestio-swagger"
    restart: always
    image: docker.swagger.io/swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      VALIDATOR_URL: "none"
      SWAGGER_JSON: /openapi.yaml
    volumes:
      - "./www/site/openapi.yaml:/openapi.yaml"
