version: "3"

services:
  db:
    image: "mysql:8.0.29"
    container_name: "tenorium-db"
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tenorium
      MYSQL_USER: tenorium
      MYSQL_PASSWORD: tenoriumpass
    ports:
      - "3306:3306"
  webserver:
    container_name: "tenorium-webserver"
    build:
      context: docker-files/tenorium-apache-php
    ports:
      - "80:80"
    volumes:
      - ./config/apache:/etc/apache2
      - ./www:/var/www
    depends_on:
      - db
  phpmyadmin:
    container_name: "tenorium-phpmyadmin"
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db
