version: "3"

services:
  apache:
    container_name: "tenorium-webserver"
    restart: always
    build:
      context: docker-files/tenorium-apache-php
    ports:
      - "80:80"
    volumes:
      - ./config/apache:/etc/apache2:delegated
      - ./www:/var/www:delegated
      - ./logs/apache2:/var/log/apache2:delegated
  nodejs:
    image: "node:17.7.1"
    volumes:
      - "./www/frontend/:/var/www/frontend/:delegated"
      - "./logs/nodejs:/root/.npm/_logs"
